<?php
# This file was automatically generated by the MediaWiki 1.29.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings
# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) )
{
	exit;
}

# Only use this file if the server is TWEBSITENAMEWITHEXTENSIONT
if
(
    $_SERVER['SERVER_NAME'] != 'localhost' &&
    $_SERVER['SERVER_NAME'] != 'wiki.TWEBSITENAMEWITHEXTENSIONT' &&
    $_SERVER['SERVER_NAME'] != 'test.TWEBSITENAMEWITHEXTENSIONT' &&
    $_SERVER['SERVER_NAME'] != 'development.TWEBSITENAMEWITHEXTENSIONT' &&
    $_SERVER['SERVER_NAME'] != 'master.TWEBSITENAMEWITHEXTENSIONT' &&
    $_SERVER['SERVER_NAME'] != 'www.TWEBSITENAMEWITHEXTENSIONT' &&
    $_SERVER['SERVER_NAME'] != 'TWEBSITENAMEWITHEXTENSIONT'
)
{
    return false;
}

# Check if /TAPPLICATIONLOWERCASENAMET/ is in the localhost path to avoid loading the wrong application settings.
if ( $_SERVER['SERVER_NAME'] == 'localhost' ) 
{
    if ( strpos( $_SERVER['REQUEST_URI'], '/TAPPLICATIONLOWERCASENAMET/') == false ) 
    {
        return false;
    }
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "TWIKISITENAMET";
$wgMetaNamespace = "Project";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
## The protocol and server name to use in fully-qualified URLs
$wgExtensionDirectory = realpath( 'TINSTALLDIRECTORYT/controller/vendor/mediawiki/extensions/' );
$wgStyleDirectory = realpath( 'TINSTALLDIRECTORYT/controller/vendor/mediawiki/skins/' );
//$wgStylePath = "http://www.TWEBSITENAMEWITHEXTENSIONT/images/wiki/skins";

$wgScriptPath = "";
if( $_SERVER['SERVER_NAME'] == 'wiki.TWEBSITENAMEWITHEXTENSIONT' )
{
    $wgServer = "http://wiki.TWEBSITENAMEWITHEXTENSIONT";
}
elseif ( $_SERVER['SERVER_NAME'] == 'localhost' ) 
{
    $wgScriptPath = substr($_SERVER['REQUEST_URI'], 0, strrpos($_SERVER['REQUEST_URI'], 'wiki') + strlen( 'wiki' ) );
    $wgServer = "http://localhost" ; 
}
else
{
    $wgScriptPath = "/wiki";
    switch ( apache_getenv( "TAPACHEAPPLICATIONENVT" ) )
    {
        case "production":
            $wgServer = "http://www.TWEBSITENAMEWITHEXTENSIONT";
            break;
        case "test":
            $wgServer = "http://test.TWEBSITENAMEWITHEXTENSIONT";
             break;
        case "development":
            $wgServer = "http://development.TWEBSITENAMEWITHEXTENSIONT";
             break;
        case "master":
            $wgServer = "http://master.TWEBSITENAMEWITHEXTENSIONT";
             break;
        default:
            $wgServer = "http://www.TWEBSITENAMEWITHEXTENSIONT";
            break;
    }
}

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";

switch ( apache_getenv( "TAPACHEAPPLICATIONENVT" ) )
{
    case "production":
        $wgDBname    = 'TDATABASEPREFIXT_production';
        break;
    case "test":
        $wgDBname    = 'TDATABASEPREFIXT_test';
        break;
    case "development":
        $wgDBname    = 'TDATABASEPREFIXT_development';
        break;
    case "master":
        $wgDBname    = 'TDATABASEPREFIXT_master';
        break;
    default:
        $wgDBname    = 'TDATABASEPREFIXT_production';
        break;
}

$wgDBuser = "TDATABASEUSERT";
$wgDBpassword = "TDATABASEPASSWORDT";

# MySQL specific settings
$wgDBprefix = "wiki_";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['read'] = true;

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':

return true;
